Email tracking
aws-quickstart/quickstart-armory-enterprise pull request #48
Opened 2021-08-13 17:08 UTC by mcgonagle

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-08-16 18:14 UTC, troy-ameigh commented
/do-e2e-tests

2021-08-18 16:29 UTC, troy-ameigh commented
/do-e2e-tests

2021-08-18 20:27 UTC, troy-ameigh requested changes
Need to understand why the email is needed.

2021-08-30 20:01 UTC, gargana commented
Closing as per discussion.

2021-08-30 20:01 UTC, closed without merging